#!/bin/bash

eex() { echo "$@"; exit 1; }

echo $#
[[ "$#" =~ ^(1|2)$ ]] && [[ "$1" =~ ^(-r.*|-c.*)$ ]] || eex "Usage: stats {-rows|-cols} [file]"
[ "$#" -eq 2 ] && [ -r "$2" ] || eex "$0: cannot read $2"


echo good result

